/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * Scenes/PhysicsGameMain.ls
 */
export class PhysicsGameMainRTBase extends Laya.Scene {
    public tipLbll: Laya.Label;
    public scoreLbl: Laya.Label;
}

