/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * Scenes/uiDemo/page/OpenScene.ls
 */
export class OpenSceneBase extends Laya.Scene {
    public window: Laya.Image;
    public closeBtn: Laya.Button;
}

