/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * prefab&#x2F;uiDemo&#x2F;list&#x2F;BagList.lh
 */
export class BagListRTBase extends Laya.View {
    public bagList: Laya.List;
    public tips: Laya.Image;
    public itemImg: Laya.Image;
    public itemNumber: Laya.Label;
    public itemReadme: Laya.TextArea;
}

