/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * prefab&#x2F;uiDemo&#x2F;list&#x2F;TreeList.lh
 */
export class TreeListRTBase extends Laya.View {
    public tree1: Laya.Tree;
    public tree2: Laya.Tree;
}

