/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * Scenes/uiDemo/page/Dialog.ls
 */
export class DialogRTBase extends Laya.Scene {
    public dialogTitle: Laya.Label;
    public closeBtn: Laya.Button;
    public dialogText: Laya.TextArea;
}

