/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/uiDemo/useUI/Progress.lh
 */
export class ProgressRTBase extends Laya.View {
    public loading2: Laya.ProgressBar;
    public loadText: Laya.Text;
}

